# Generated by Django 3.2.4 on 2021-08-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='Cours',
        ),
    ]
